_wandb:
    value:
        cli_version: 0.22.3
        e:
            hamviq5uneg3i2o929p40doavxinybb9:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8053063680"
                args:
                    - app:app
                    - --host
                    - 0.0.0.0
                    - --port
                    - "8000"
                    - --reload
                codePath: venv/bin/uvicorn
                codePathLocal: venv/bin/uvicorn
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236676927488"
                email: harshaab@buffalo.edu
                executable: /Users/harshaabhinavkusampudi/Documents/Agent/backend/venv/bin/python3
                host: Harshas-MacBook-Air-5.local
                memory:
                    total: "8589934592"
                os: macOS-15.3-arm64-arm-64bit
                program: /Users/harshaabhinavkusampudi/Documents/Agent/backend/venv/bin/uvicorn
                python: CPython 3.12.9
                root: /Users/harshaabhinavkusampudi/Documents/Agent/backend
                startedAt: "2025-11-04T20:14:27.524770Z"
                writerId: hamviq5uneg3i2o929p40doavxinybb9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.3
            "6": 4.57.1
            "10":
                - 21
            "12": 0.22.3
            "13": darwin-arm64
batch_size:
    value: 4
dataset_path:
    value: backend/uploads/test_sentiment.csv
epochs:
    value: 1
label_col:
    value: label
learning_rate:
    value: 5e-05
model:
    value: distilbert-base-uncased
num_labels:
    value: 2
text_col:
    value: text
