_wandb:
    value:
        cli_version: 0.22.3
        e:
            qmlh7ljg3y1qmh3i7zvcv2k7knryg1li:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8053063680"
                args:
                    - app:app
                    - --host
                    - 0.0.0.0
                    - --port
                    - "8000"
                    - --reload
                codePath: venv/bin/uvicorn
                codePathLocal: venv/bin/uvicorn
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236669476864"
                email: harshaab@buffalo.edu
                executable: /Users/harshaabhinavkusampudi/Documents/Agent/backend/venv/bin/python3
                host: Harshas-MacBook-Air-5.local
                memory:
                    total: "8589934592"
                os: macOS-15.3-arm64-arm-64bit
                program: /Users/harshaabhinavkusampudi/Documents/Agent/backend/venv/bin/uvicorn
                python: CPython 3.12.9
                root: /Users/harshaabhinavkusampudi/Documents/Agent/backend
                startedAt: "2025-11-04T20:02:41.101626Z"
                writerId: qmlh7ljg3y1qmh3i7zvcv2k7knryg1li
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.3
            "6": 4.57.1
            "10":
                - 21
            "12": 0.22.3
            "13": darwin-arm64
config:
    value:
        batch_size: 16
        epochs: 3
        learning_rate: 3e-05
        max_seq_length: 128
        use_peft: true
        warmup_steps: 500
        weight_decay: 0.01
dataset_path:
    value: uploads/09376719-c3cb-475c-b641-fcda07ab9137_test_sentiment.csv
model:
    value: distilbert-base-uncased
