"""
Predefined model catalog for ModelForge.
ModelAgent consults this catalog before reasoning from scratch — for common
use cases this gives consistent, well-validated recommendations without
burning Claude tokens on model selection every time.

Each entry is a dict with stable keys so the ModelAgent prompt can embed
them as structured JSON context.
"""
from __future__ import annotations

from typing import Any

MODEL_CATALOG: list[dict[str, Any]] = [
    # ── Small & Efficient (< 100M) ────────────────────────────────────────────
    {
        "model_id": "albert-base-v2",
        "display_name": "ALBERT Base v2",
        "task_types": ["text_classification", "ner"],
        "param_count": "11M",
        "param_count_int": 11_000_000,
        "training_data_min": 100,
        "training_data_sweet_spot": 5_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "fast",
        "languages": ["en"],
        "description": "Ultra-lightweight BERT variant using parameter sharing for fast inference and low memory.",
        "best_for": "Resource-constrained environments, mobile deployment, or quick prototyping with small datasets.",
        "tags": ["small", "fast", "efficient", "english"],
    },
    {
        "model_id": "microsoft/electra-small-discriminator",
        "display_name": "ELECTRA Small",
        "task_types": ["text_classification", "ner"],
        "param_count": "14M",
        "param_count_int": 14_000_000,
        "training_data_min": 100,
        "training_data_sweet_spot": 5_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "fast",
        "languages": ["en"],
        "description": "GAN-style pre-trained tiny classifier. Competitive performance for its parameter count.",
        "best_for": "Quick experiments on edge devices or when fine-tuning budget is minimal.",
        "tags": ["small", "fast", "efficient", "english"],
    },
    {
        "model_id": "distilbert-base-uncased",
        "display_name": "DistilBERT Base",
        "task_types": ["text_classification", "ner"],
        "param_count": "67M",
        "param_count_int": 67_000_000,
        "training_data_min": 200,
        "training_data_sweet_spot": 10_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "balanced",
        "languages": ["en"],
        "description": "2x faster and 40% smaller than BERT while retaining 97% of its performance.",
        "best_for": "The default choice for most English text classification tasks. Fast inference, great balance of speed and accuracy.",
        "tags": ["small", "fast", "distilled", "english", "production-ready"],
    },
    {
        "model_id": "microsoft/MiniLM-L12-H384-uncased",
        "display_name": "MiniLM L12",
        "task_types": ["text_classification", "ner", "semantic_similarity"],
        "param_count": "33M",
        "param_count_int": 33_000_000,
        "training_data_min": 150,
        "training_data_sweet_spot": 8_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "balanced",
        "languages": ["en"],
        "description": "3x smaller than BERT-base with 2.7x faster inference via self-attention distillation.",
        "best_for": "Production inference on limited hardware. Often outperforms BERT-base despite being 3x smaller.",
        "tags": ["small", "fast", "distilled", "efficient", "english"],
    },
    {
        "model_id": "microsoft/deberta-v3-small",
        "display_name": "DeBERTa v3 Small",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "44M",
        "param_count_int": 44_000_000,
        "training_data_min": 200,
        "training_data_sweet_spot": 8_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "balanced",
        "languages": ["en"],
        "description": "Compact DeBERTa with disentangled attention — better generalization than BERT at similar size.",
        "best_for": "When you want strong baseline performance without large model overhead.",
        "tags": ["small", "accurate", "disentangled-attention", "english"],
    },
    # ── Medium (100M – 150M) ──────────────────────────────────────────────────
    {
        "model_id": "distilroberta-base",
        "display_name": "DistilRoBERTa Base",
        "task_types": ["text_classification", "ner"],
        "param_count": "82M",
        "param_count_int": 82_000_000,
        "training_data_min": 300,
        "training_data_sweet_spot": 10_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "balanced",
        "languages": ["en"],
        "description": "RoBERTa distilled to 2x faster with minimal accuracy loss.",
        "best_for": "When you want RoBERTa quality with better inference speed.",
        "tags": ["small", "fast", "distilled", "english"],
    },
    {
        "model_id": "bert-base-uncased",
        "display_name": "BERT Base Uncased",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "110M",
        "param_count_int": 110_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 20_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "The industry-standard baseline — bidirectional BERT trained on Wikipedia + BookCorpus.",
        "best_for": "When you need a reliable baseline or have moderate compute. Most extensive community support.",
        "tags": ["balanced", "accurate", "standard", "english"],
    },
    {
        "model_id": "bert-base-cased",
        "display_name": "BERT Base Cased",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "110M",
        "param_count_int": 110_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 20_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "BERT base with case preserved — important for proper nouns and NER.",
        "best_for": "NER and any task where capitalization is a meaningful signal (e.g. person names, locations).",
        "tags": ["balanced", "accurate", "cased", "ner", "english"],
    },
    {
        "model_id": "roberta-base",
        "display_name": "RoBERTa Base",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "125M",
        "param_count_int": 125_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 20_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "Robustly optimized BERT with dynamic masking — consistently outperforms BERT on benchmarks.",
        "best_for": "Standard choice for maximum BERT-class performance. Strongly recommended over BERT for new projects.",
        "tags": ["balanced", "accurate", "robust", "english"],
    },
    {
        "model_id": "microsoft/deberta-v3-base",
        "display_name": "DeBERTa v3 Base",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "86M",
        "param_count_int": 86_000_000,
        "training_data_min": 300,
        "training_data_sweet_spot": 15_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "Disentangled attention + ELECTRA pre-training — outperforms BERT-base on most NLU tasks.",
        "best_for": "Balanced accuracy/speed choice. Strong GLUE and SQuAD performance.",
        "tags": ["balanced", "accurate", "disentangled-attention", "english"],
    },
    {
        "model_id": "google/electra-base-discriminator",
        "display_name": "ELECTRA Base",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "110M",
        "param_count_int": 110_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 20_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "GAN-style discriminator pre-training achieves superior compute-efficiency vs BERT.",
        "best_for": "Resource-efficient training with strong downstream performance.",
        "tags": ["balanced", "accurate", "efficient", "english"],
    },
    # ── Multilingual ──────────────────────────────────────────────────────────
    {
        "model_id": "xlm-roberta-base",
        "display_name": "XLM-RoBERTa Base",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "270M",
        "param_count_int": 270_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 20_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en", "fr", "de", "es", "it", "pt", "ru", "zh", "ja", "ar", "hi", "th", "vi", "ko",
                      "nl", "pl", "sv", "da", "fi", "no", "tr", "id", "ms", "cs", "ro", "hu"],
        "description": "RoBERTa pre-trained on 2.5TB CommonCrawl across 100 languages.",
        "best_for": "Multilingual projects or non-English datasets. Zero-shot cross-lingual transfer.",
        "tags": ["multilingual", "100-languages", "accurate"],
    },
    {
        "model_id": "distilbert-base-multilingual-cased",
        "display_name": "DistilBERT Multilingual",
        "task_types": ["text_classification", "ner"],
        "param_count": "134M",
        "param_count_int": 134_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 15_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "balanced",
        "languages": ["en", "fr", "de", "es", "it", "pt", "nl", "ru", "ar", "zh", "ja", "ko"],
        "description": "2x faster multilingual BERT across 104 languages.",
        "best_for": "Multilingual projects with inference speed constraints.",
        "tags": ["multilingual", "fast", "104-languages"],
    },
    # ── Large (300M+) ─────────────────────────────────────────────────────────
    {
        "model_id": "roberta-large",
        "display_name": "RoBERTa Large",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "355M",
        "param_count_int": 355_000_000,
        "training_data_min": 1_000,
        "training_data_sweet_spot": 50_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "slow",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "Large RoBERTa — SOTA on many classification benchmarks.",
        "best_for": "When absolute accuracy is paramount and you have >1K examples. Top performer on GLUE.",
        "tags": ["large", "accurate", "sota", "english"],
    },
    {
        "model_id": "microsoft/deberta-v3-large",
        "display_name": "DeBERTa v3 Large",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "304M",
        "param_count_int": 304_000_000,
        "training_data_min": 1_000,
        "training_data_sweet_spot": 50_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "slow",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "Large DeBERTa achieving top-tier MNLI and SQuAD scores.",
        "best_for": "Competitive benchmarking where accuracy > latency.",
        "tags": ["large", "sota", "accurate", "english"],
    },
    {
        "model_id": "xlm-roberta-large",
        "display_name": "XLM-RoBERTa Large",
        "task_types": ["text_classification", "ner", "question_answering"],
        "param_count": "550M",
        "param_count_int": 550_000_000,
        "training_data_min": 1_000,
        "training_data_sweet_spot": 50_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "slow",
        "quality_tier": "accurate",
        "languages": ["en", "fr", "de", "es", "it", "pt", "ru", "zh", "ja", "ar", "hi", "th", "vi", "ko"],
        "description": "Large XLM-RoBERTa — peak multilingual accuracy.",
        "best_for": "Multilingual projects where accuracy is critical over inference speed.",
        "tags": ["multilingual", "large", "accurate", "100-languages"],
    },
    # ── Text Generation ───────────────────────────────────────────────────────
    {
        "model_id": "distilgpt2",
        "display_name": "DistilGPT-2",
        "task_types": ["text_generation", "language_modeling"],
        "param_count": "82M",
        "param_count_int": 82_000_000,
        "training_data_min": 1_000,
        "training_data_sweet_spot": 50_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "fast",
        "languages": ["en"],
        "description": "GPT-2 distilled to 66% size. Fast English text generation.",
        "best_for": "Quick text generation on edge devices. Autocomplete, creative writing, entertainment.",
        "tags": ["small", "fast", "text-generation", "english"],
    },
    {
        "model_id": "gpt2",
        "display_name": "GPT-2",
        "task_types": ["text_generation", "language_modeling"],
        "param_count": "124M",
        "param_count_int": 124_000_000,
        "training_data_min": 1_000,
        "training_data_sweet_spot": 50_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "balanced",
        "languages": ["en"],
        "description": "OpenAI GPT-2 — industry standard for open-source text generation.",
        "best_for": "Text generation with good quality/speed balance. Extensive fine-tuning examples available.",
        "tags": ["balanced", "text-generation", "english"],
    },
    {
        "model_id": "google/flan-t5-small",
        "display_name": "FLAN-T5 Small",
        "task_types": ["text_generation", "summarization", "question_answering", "instruction_following"],
        "param_count": "77M",
        "param_count_int": 77_000_000,
        "training_data_min": 500,
        "training_data_sweet_spot": 50_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "fast",
        "quality_tier": "balanced",
        "languages": ["en", "multilingual"],
        "description": "T5-Small instruction-tuned on 1000+ tasks across 55+ languages.",
        "best_for": "Zero-shot and few-shot learning without fine-tuning. Multi-task NLP across many languages.",
        "tags": ["small", "instruction-following", "zero-shot", "multilingual"],
    },
    {
        "model_id": "t5-base",
        "display_name": "T5 Base",
        "task_types": ["text_generation", "summarization", "translation", "question_answering", "text_classification"],
        "param_count": "220M",
        "param_count_int": 220_000_000,
        "training_data_min": 2_000,
        "training_data_sweet_spot": 100_000,
        "lora_compatible": True,
        "qlora_compatible": True,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en", "fr", "de", "ro"],
        "description": "Unified text-to-text framework for 13+ tasks. Strong few-shot capabilities.",
        "best_for": "Multi-task fine-tuning: generation, summarization, and classification in one model.",
        "tags": ["balanced", "text-generation", "multi-task", "accurate"],
    },
    # ── Pre-fine-tuned (zero additional training needed) ──────────────────────
    {
        "model_id": "distilbert-base-uncased-finetuned-sst-2-english",
        "display_name": "DistilBERT Sentiment (SST-2)",
        "task_types": ["text_classification", "sentiment_analysis"],
        "param_count": "67M",
        "param_count_int": 67_000_000,
        "training_data_min": 0,
        "training_data_sweet_spot": 0,
        "lora_compatible": False,
        "qlora_compatible": False,
        "inference_speed": "fast",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "DistilBERT pre-fine-tuned for sentiment analysis — 91.3% on SST-2. Use as-is.",
        "best_for": "Binary sentiment classification without any training. Direct inference only.",
        "tags": ["pre-tuned", "sentiment-analysis", "fast", "zero-training"],
    },
    {
        "model_id": "cardiffnlp/twitter-roberta-base-sentiment",
        "display_name": "Twitter-RoBERTa Sentiment",
        "task_types": ["text_classification", "sentiment_analysis"],
        "param_count": "125M",
        "param_count_int": 125_000_000,
        "training_data_min": 0,
        "training_data_sweet_spot": 0,
        "lora_compatible": False,
        "qlora_compatible": False,
        "inference_speed": "medium",
        "quality_tier": "accurate",
        "languages": ["en"],
        "description": "RoBERTa trained on 58M tweets. 3-class sentiment (negative/neutral/positive).",
        "best_for": "Social media, tweets, and informal text sentiment analysis. Use as-is.",
        "tags": ["pre-tuned", "sentiment-analysis", "social-media", "zero-training"],
    },
]

# Fast lookup by model_id
_CATALOG_INDEX: dict[str, dict] = {m["model_id"]: m for m in MODEL_CATALOG}


def get_model(model_id: str) -> dict | None:
    return _CATALOG_INDEX.get(model_id)


def filter_catalog(
    task_type: str | None = None,
    max_params: int | None = None,
    min_training_rows: int | None = None,
    languages: list[str] | None = None,
    lora_only: bool = False,
) -> list[dict]:
    """Return catalog entries matching the given constraints, ordered by param_count_int."""
    results = []
    for model in MODEL_CATALOG:
        if task_type and task_type not in model["task_types"]:
            continue
        if max_params and model["param_count_int"] > max_params:
            continue
        if min_training_rows is not None and model["training_data_min"] > min_training_rows:
            continue
        if languages:
            model_langs = model.get("languages", [])
            if not any(lang in model_langs for lang in languages):
                continue
        if lora_only and not model.get("lora_compatible"):
            continue
        results.append(model)
    return sorted(results, key=lambda m: m["param_count_int"])


def catalog_summary_for_prompt() -> str:
    """Return a compact JSON string of the catalog suitable for embedding in a Claude prompt."""
    import json
    compact = [
        {
            "model_id": m["model_id"],
            "display_name": m["display_name"],
            "task_types": m["task_types"],
            "params": m["param_count"],
            "speed": m["inference_speed"],
            "quality": m["quality_tier"],
            "languages": m["languages"],
            "min_rows": m["training_data_min"],
            "lora": m["lora_compatible"],
            "best_for": m["best_for"],
        }
        for m in MODEL_CATALOG
    ]
    return json.dumps(compact, indent=2)
