"""
Predefined model catalog for ModelForge.
Covers encoders, seq2seq, decoders/LLMs, multilingual, domain-specific,
embedding, vision, and cloud-API fine-tuning providers.

Fields
------
model_id           : HuggingFace model ID (or "provider/name" for API models)
display_name       : Human-readable label
category           : encoder | seq2seq | decoder | embedding | vision | api
provider           : huggingface | openai | cohere | google
param_count        : human-readable size string
param_count_m      : numeric millions (for filtering)
task_types         : list of supported task type strings
quality_tier       : excellent | good | balanced | fast
inference_speed    : fast | medium | slow
lora_compatible    : True if PEFT LoRA works
qlora_compatible   : True if 4-bit QLoRA is feasible
training_data_min  : minimum recommended rows
languages          : ["en"] or ["multilingual"]
description        : one-sentence description
best_for           : one-sentence use-case guidance
tags               : searchable keywords
requires_token     : True for gated models (Llama, Gemma, etc.)
license            : SPDX identifier
"""
from __future__ import annotations
from typing import Any

CATALOG: list[dict[str, Any]] = [

    # ══════════════════════════════════════════════════════════════════════
    # ENCODERS — tiny / small  (<100M)
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "albert-base-v2",
        "display_name": "ALBERT Base v2",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "11M",
        "param_count_m": 11,
        "task_types": ["text_classification", "ner", "sentiment_analysis"],
        "quality_tier": "fast",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 100,
        "languages": ["en"],
        "description": "Ultra-lightweight BERT variant using parameter sharing for tiny footprint.",
        "best_for": "Edge deployment, mobile, or quick experiments on small datasets.",
        "tags": ["small", "fast", "efficient", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "microsoft/electra-small-discriminator",
        "display_name": "ELECTRA Small",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "14M",
        "param_count_m": 14,
        "task_types": ["text_classification", "ner"],
        "quality_tier": "fast",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 100,
        "languages": ["en"],
        "description": "GAN-style pre-training with replaced token detection — competitive for its size.",
        "best_for": "Quick experiments where speed matters more than top accuracy.",
        "tags": ["small", "fast", "electra", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "microsoft/MiniLM-L12-H384-uncased",
        "display_name": "MiniLM-L12",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "33M",
        "param_count_m": 33,
        "task_types": ["text_classification", "ner", "semantic_similarity"],
        "quality_tier": "balanced",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 150,
        "languages": ["en"],
        "description": "3× smaller than BERT-base via self-attention distillation with minimal accuracy loss.",
        "best_for": "Production APIs that need sub-50ms latency with good classification quality.",
        "tags": ["small", "fast", "distilled", "minilm", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "distilbert-base-uncased",
        "display_name": "DistilBERT Base Uncased",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "67M",
        "param_count_m": 67,
        "task_types": ["text_classification", "ner", "sentiment_analysis"],
        "quality_tier": "balanced",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "2× faster and 40% smaller than BERT while retaining 97% performance. The go-to default.",
        "best_for": "Most English classification tasks where you want speed + good accuracy.",
        "tags": ["popular", "fast", "distilled", "english", "classification", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "distilroberta-base",
        "display_name": "DistilRoBERTa Base",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "82M",
        "param_count_m": 82,
        "task_types": ["text_classification", "sentiment_analysis", "ner"],
        "quality_tier": "balanced",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "Distilled RoBERTa — best speed/accuracy tradeoff among the distilled family.",
        "best_for": "Speed-sensitive services that still want RoBERTa-quality representations.",
        "tags": ["fast", "distilled", "roberta", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ENCODERS — medium (100M – 200M)
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "bert-base-uncased",
        "display_name": "BERT Base Uncased",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["text_classification", "ner", "sentiment_analysis", "question_answering"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Google's original BERT. Solid, well-understood baseline for almost any NLP task.",
        "best_for": "General-purpose fine-tuning with well-established recipes and abundant documentation.",
        "tags": ["popular", "classic", "bert", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "bert-base-cased",
        "display_name": "BERT Base Cased",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["text_classification", "ner"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Case-preserving BERT. Better for NER, proper nouns, and tasks where capitalisation is signal.",
        "best_for": "Named entity recognition and tasks where 'Apple' ≠ 'apple' matters.",
        "tags": ["bert", "cased", "ner", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "roberta-base",
        "display_name": "RoBERTa Base",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "125M",
        "param_count_m": 125,
        "task_types": ["text_classification", "sentiment_analysis", "ner"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Robustly optimised BERT — longer training, more data, no NSP. Beats BERT on all benchmarks.",
        "best_for": "When accuracy is the priority and speed is secondary. Top encoder for classification.",
        "tags": ["popular", "recommended", "roberta", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "xlnet-base-cased",
        "display_name": "XLNet Base Cased",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "117M",
        "param_count_m": 117,
        "task_types": ["text_classification", "sentiment_analysis", "question_answering"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Permutation-based autoregressive pre-training that captures bidirectional context.",
        "best_for": "Long-document tasks where word-order permutation helps generalisation.",
        "tags": ["xlnet", "autoregressive", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "microsoft/deberta-v3-small",
        "display_name": "DeBERTa-v3 Small",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "142M",
        "param_count_m": 142,
        "task_types": ["text_classification", "ner", "sentiment_analysis"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Microsoft's best compact encoder. Disentangled attention + enhanced mask decoder.",
        "best_for": "Maximum accuracy on structured classification tasks within a tight parameter budget.",
        "tags": ["recommended", "deberta", "microsoft", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "microsoft/deberta-v3-base",
        "display_name": "DeBERTa-v3 Base",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "184M",
        "param_count_m": 184,
        "task_types": ["text_classification", "ner", "sentiment_analysis", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["en"],
        "description": "Full DeBERTa-v3 base — consistently top of GLUE benchmarks among base-size models.",
        "best_for": "Highest accuracy per parameter for general NLP. Benchmark leader.",
        "tags": ["deberta", "microsoft", "high-accuracy", "encoder"],
        "requires_token": False,
        "license": "mit",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ENCODERS — large (300M+)
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "bert-large-uncased",
        "display_name": "BERT Large Uncased",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "340M",
        "param_count_m": 340,
        "task_types": ["text_classification", "question_answering", "ner"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["en"],
        "description": "24-layer BERT with 1024-dimensional embeddings for demanding tasks.",
        "best_for": "High-stakes classification where you have ≥2 000 rows and can afford slower inference.",
        "tags": ["large", "bert", "high-accuracy", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "roberta-large",
        "display_name": "RoBERTa Large",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "355M",
        "param_count_m": 355,
        "task_types": ["text_classification", "sentiment_analysis", "ner"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["en"],
        "description": "Large-scale RoBERTa — best-in-class encoder for high-resource scenarios.",
        "best_for": "When you need the absolute best classification accuracy and have plenty of data.",
        "tags": ["large", "roberta", "high-accuracy", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "microsoft/deberta-v3-large",
        "display_name": "DeBERTa-v3 Large",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "434M",
        "param_count_m": 434,
        "task_types": ["text_classification", "ner", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["en"],
        "description": "Largest DeBERTa-v3. State-of-the-art on SuperGLUE and most NLU benchmarks.",
        "best_for": "Competition-grade accuracy with no resource constraints.",
        "tags": ["large", "deberta", "microsoft", "sota", "encoder"],
        "requires_token": False,
        "license": "mit",
    },

    # ══════════════════════════════════════════════════════════════════════
    # DOMAIN-SPECIFIC (Pre-fine-tuned encoders)
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "cardiffnlp/twitter-roberta-base-sentiment-latest",
        "display_name": "Twitter RoBERTa Sentiment",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "125M",
        "param_count_m": 125,
        "task_types": ["sentiment_analysis", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "RoBERTa fine-tuned on 124M tweets. Best out-of-the-box for social media sentiment.",
        "best_for": "Twitter / Reddit / social-media sentiment with minimal additional training data.",
        "tags": ["domain-specific", "sentiment", "twitter", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "ProsusAI/finbert",
        "display_name": "FinBERT",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["sentiment_analysis", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "BERT pre-trained on financial news + fine-tuned for financial sentiment.",
        "best_for": "Financial news sentiment, earnings-call analysis, market sentiment.",
        "tags": ["domain-specific", "finance", "sentiment", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "dmis-lab/biobert-base-cased-v1.2",
        "display_name": "BioBERT Base",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["ner", "text_classification", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 300,
        "languages": ["en"],
        "description": "BERT pre-trained on PubMed abstracts and PMC full-text articles.",
        "best_for": "Biomedical NER (disease, gene, drug), clinical text classification.",
        "tags": ["domain-specific", "biomedical", "medical", "ner", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "nlpaueb/legal-bert-base-uncased",
        "display_name": "Legal BERT",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["text_classification", "ner"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 300,
        "languages": ["en"],
        "description": "BERT pre-trained on US court opinions and legislation from the Harvard Law corpus.",
        "best_for": "Legal contract classification, statute analysis, case outcome prediction.",
        "tags": ["domain-specific", "legal", "law", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "dslim/bert-base-NER",
        "display_name": "BERT NER (CoNLL-2003)",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["ner"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "BERT fine-tuned on CoNLL-2003 NER benchmark (PER, ORG, LOC, MISC).",
        "best_for": "Jump-start NER on custom entity types with minimal domain data.",
        "tags": ["domain-specific", "ner", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "yiyanghkust/finbert-tone",
        "display_name": "FinBERT Tone",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["sentiment_analysis", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "FinBERT variant fine-tuned on forward-looking statements for tone detection.",
        "best_for": "Analyst report tone, earnings call sentiment, forward guidance classification.",
        "tags": ["domain-specific", "finance", "sentiment", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },

    # ══════════════════════════════════════════════════════════════════════
    # MULTILINGUAL ENCODERS
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "bert-base-multilingual-cased",
        "display_name": "mBERT Base (104 langs)",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "178M",
        "param_count_m": 178,
        "task_types": ["text_classification", "ner", "sentiment_analysis"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["multilingual"],
        "description": "Original multilingual BERT supporting 104 languages for zero-shot cross-lingual transfer.",
        "best_for": "Cross-lingual classification when your dataset spans multiple languages.",
        "tags": ["multilingual", "cross-lingual", "encoder"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "xlm-roberta-base",
        "display_name": "XLM-RoBERTa Base (100 langs)",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "278M",
        "param_count_m": 278,
        "task_types": ["text_classification", "ner", "sentiment_analysis"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["multilingual"],
        "description": "Multilingual RoBERTa trained on 2.5TB of web data in 100 languages. Best multilingual encoder.",
        "best_for": "Any multilingual classification — the gold standard for cross-lingual NLP.",
        "tags": ["multilingual", "recommended", "cross-lingual", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "xlm-roberta-large",
        "display_name": "XLM-RoBERTa Large (100 langs)",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "560M",
        "param_count_m": 560,
        "task_types": ["text_classification", "ner", "sentiment_analysis"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["multilingual"],
        "description": "Large-scale multilingual RoBERTa. Best multilingual accuracy available.",
        "best_for": "Multilingual tasks requiring maximum accuracy with no latency constraint.",
        "tags": ["multilingual", "large", "cross-lingual", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "microsoft/mdeberta-v3-base",
        "display_name": "mDeBERTa-v3 Base (100 langs)",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "278M",
        "param_count_m": 278,
        "task_types": ["text_classification", "ner", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["multilingual"],
        "description": "Multilingual DeBERTa-v3 — best XNLI and cross-lingual benchmark scores.",
        "best_for": "Highest accuracy multilingual classification especially for European languages.",
        "tags": ["multilingual", "deberta", "microsoft", "encoder"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "nlptown/bert-base-multilingual-uncased-sentiment",
        "display_name": "Multilingual Sentiment BERT",
        "category": "encoder",
        "provider": "huggingface",
        "param_count": "167M",
        "param_count_m": 167,
        "task_types": ["sentiment_analysis"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 200,
        "languages": ["multilingual"],
        "description": "mBERT fine-tuned on product reviews in 6 languages for star-rating sentiment.",
        "best_for": "Product reviews, e-commerce sentiment in English, Dutch, German, French, Spanish, Italian.",
        "tags": ["multilingual", "sentiment", "pre-finetuned", "encoder"],
        "requires_token": False,
        "license": "mit",
    },

    # ══════════════════════════════════════════════════════════════════════
    # SEQ2SEQ MODELS
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "t5-small",
        "display_name": "T5 Small",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "60M",
        "param_count_m": 60,
        "task_types": ["text_generation", "summarization", "translation", "question_answering"],
        "quality_tier": "fast",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Smallest T5 variant from Google. Text-to-text framework for any NLP task.",
        "best_for": "Summarisation, translation, and QA when compute is limited.",
        "tags": ["seq2seq", "t5", "generation", "google"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "t5-base",
        "display_name": "T5 Base",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "220M",
        "param_count_m": 220,
        "task_types": ["text_generation", "summarization", "translation", "question_answering"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["en"],
        "description": "Balanced T5 for text-to-text tasks. Trained on C4 with multi-task objectives.",
        "best_for": "General summarisation, translation, and conditional text generation.",
        "tags": ["seq2seq", "t5", "generation", "google"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "google/flan-t5-base",
        "display_name": "FLAN-T5 Base (instruction-tuned)",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "250M",
        "param_count_m": 250,
        "task_types": ["text_generation", "question_answering", "summarization", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "T5 fine-tuned on 1800+ instruction tasks via FLAN. Follows instructions well.",
        "best_for": "Few-shot and zero-shot tasks, instruction-following, NLI, and QA.",
        "tags": ["seq2seq", "flan", "instruction-tuned", "google", "zero-shot"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "google/flan-t5-large",
        "display_name": "FLAN-T5 Large",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "780M",
        "param_count_m": 780,
        "task_types": ["text_generation", "question_answering", "summarization"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["en"],
        "description": "Large instruction-tuned T5. Strong out-of-the-box reasoning with minimal fine-tuning.",
        "best_for": "Complex QA, chain-of-thought tasks, and high-quality summarisation.",
        "tags": ["seq2seq", "flan", "instruction-tuned", "large", "google"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "facebook/bart-base",
        "display_name": "BART Base",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "139M",
        "param_count_m": 139,
        "task_types": ["summarization", "text_generation", "text_classification"],
        "quality_tier": "good",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Denoising auto-encoder combining BERT and GPT. Strong for summarisation and generation.",
        "best_for": "Abstractive summarisation, paraphrase generation, and seq2seq tasks.",
        "tags": ["seq2seq", "bart", "summarization", "generation", "meta"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "facebook/bart-large-cnn",
        "display_name": "BART Large CNN (summarisation)",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "407M",
        "param_count_m": 407,
        "task_types": ["summarization"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "BART large fine-tuned on CNN/DailyMail. The reference model for news summarisation.",
        "best_for": "News article, document, or report summarisation tasks.",
        "tags": ["seq2seq", "summarization", "pre-finetuned", "large", "meta"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "google/mt5-base",
        "display_name": "mT5 Base (101 langs)",
        "category": "seq2seq",
        "provider": "huggingface",
        "param_count": "580M",
        "param_count_m": 580,
        "task_types": ["text_generation", "summarization", "translation"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["multilingual"],
        "description": "Multilingual T5 pre-trained on mC4 covering 101 languages.",
        "best_for": "Multilingual summarisation and generation across many languages.",
        "tags": ["seq2seq", "multilingual", "t5", "generation", "google"],
        "requires_token": False,
        "license": "apache-2.0",
    },

    # ══════════════════════════════════════════════════════════════════════
    # DECODER / LLM (for LoRA fine-tuning)
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "gpt2",
        "display_name": "GPT-2 (124M)",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "124M",
        "param_count_m": 124,
        "task_types": ["text_generation"],
        "quality_tier": "fast",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "OpenAI's classic autoregressive LM. Simple to fine-tune for domain-specific generation.",
        "best_for": "Text completion, domain-specific language generation with small datasets.",
        "tags": ["decoder", "gpt2", "generation", "small-llm"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "EleutherAI/pythia-410m",
        "display_name": "Pythia 410M",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "410M",
        "param_count_m": 410,
        "task_types": ["text_generation"],
        "quality_tier": "balanced",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["en"],
        "description": "EleutherAI's reproducible, interpretable LM trained on The Pile with full training logs.",
        "best_for": "Research, ablation studies, and lightweight generative fine-tuning.",
        "tags": ["decoder", "pythia", "open-source", "generation", "eleutherai"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        "display_name": "TinyLlama 1.1B Chat",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "1.1B",
        "param_count_m": 1100,
        "task_types": ["text_generation", "question_answering"],
        "quality_tier": "balanced",
        "inference_speed": "fast",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["en"],
        "description": "Llama-2 architecture at 1.1B — surprisingly capable for its size, chat fine-tuned.",
        "best_for": "On-device LLM tasks, chat fine-tuning, and edge deployment with LoRA.",
        "tags": ["decoder", "llm", "small", "chat", "lora-optimized"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "microsoft/phi-2",
        "display_name": "Phi-2 (2.7B)",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "2.7B",
        "param_count_m": 2700,
        "task_types": ["text_generation", "question_answering", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["en"],
        "description": "Microsoft's Phi-2 outperforms models 5× larger on many benchmarks. Trained on 'textbook quality' data.",
        "best_for": "High-quality instruction following, QA, and classification with LoRA.",
        "tags": ["decoder", "llm", "microsoft", "phi", "efficient", "recommended"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "mistralai/Mistral-7B-v0.1",
        "display_name": "Mistral 7B",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "7B",
        "param_count_m": 7000,
        "task_types": ["text_generation", "question_answering", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["en"],
        "description": "Mistral AI's flagship open 7B model. Beats Llama-2-13B on most benchmarks.",
        "best_for": "High-quality text generation, instruction following, and classification with QLoRA.",
        "tags": ["decoder", "llm", "7b", "mistral", "qlora-optimized", "recommended"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "Qwen/Qwen2-7B",
        "display_name": "Qwen2 7B",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "7B",
        "param_count_m": 7000,
        "task_types": ["text_generation", "question_answering", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["multilingual"],
        "description": "Alibaba's Qwen2 7B — strong multilingual reasoning and coding abilities.",
        "best_for": "Multilingual generation, code tasks, and cross-lingual fine-tuning with QLoRA.",
        "tags": ["decoder", "llm", "7b", "multilingual", "qwen", "qlora-optimized"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "meta-llama/Llama-2-7b-hf",
        "display_name": "Llama 2 7B",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "7B",
        "param_count_m": 7000,
        "task_types": ["text_generation", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 2000,
        "languages": ["en"],
        "description": "Meta's widely-used open LLM. Requires HF access token (gated model).",
        "best_for": "General text generation and instruction following — requires Meta access approval.",
        "tags": ["decoder", "llm", "7b", "llama", "meta", "gated"],
        "requires_token": True,
        "license": "llama2",
    },
    {
        "model_id": "google/gemma-2b",
        "display_name": "Gemma 2B",
        "category": "decoder",
        "provider": "huggingface",
        "param_count": "2B",
        "param_count_m": 2000,
        "task_types": ["text_generation", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": True,
        "training_data_min": 1000,
        "languages": ["en"],
        "description": "Google's Gemma 2B — lightweight, high-quality decoder. Requires HF access token.",
        "best_for": "Efficient instruction following and QA. Good price/performance with LoRA.",
        "tags": ["decoder", "llm", "google", "gemma", "gated"],
        "requires_token": True,
        "license": "gemma",
    },

    # ══════════════════════════════════════════════════════════════════════
    # EMBEDDING / SENTENCE TRANSFORMER
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "sentence-transformers/all-MiniLM-L6-v2",
        "display_name": "all-MiniLM-L6-v2 (22M)",
        "category": "embedding",
        "provider": "huggingface",
        "param_count": "22M",
        "param_count_m": 22,
        "task_types": ["semantic_similarity", "clustering", "text_classification"],
        "quality_tier": "fast",
        "inference_speed": "fast",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 100,
        "languages": ["en"],
        "description": "Ultra-fast sentence embedding model. Best inference speed in its class.",
        "best_for": "Semantic search, sentence similarity, and clustering with low latency.",
        "tags": ["embedding", "sentence-transformers", "small", "fast"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "sentence-transformers/all-mpnet-base-v2",
        "display_name": "all-mpnet-base-v2 (110M)",
        "category": "embedding",
        "provider": "huggingface",
        "param_count": "110M",
        "param_count_m": 110,
        "task_types": ["semantic_similarity", "clustering", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "Best-quality general-purpose sentence embedding. Trained on 1B+ sentence pairs.",
        "best_for": "High-quality semantic search and document similarity where accuracy matters.",
        "tags": ["embedding", "sentence-transformers", "high-quality"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "BAAI/bge-small-en-v1.5",
        "display_name": "BGE Small EN v1.5",
        "category": "embedding",
        "provider": "huggingface",
        "param_count": "33M",
        "param_count_m": 33,
        "task_types": ["semantic_similarity", "clustering"],
        "quality_tier": "balanced",
        "inference_speed": "fast",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 100,
        "languages": ["en"],
        "description": "BAAI's BGE small model — tops MTEB benchmark for its size category.",
        "best_for": "RAG retrieval, fast semantic similarity with state-of-the-art small-model quality.",
        "tags": ["embedding", "bge", "rag", "fast"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "BAAI/bge-large-en-v1.5",
        "display_name": "BGE Large EN v1.5",
        "category": "embedding",
        "provider": "huggingface",
        "param_count": "335M",
        "param_count_m": 335,
        "task_types": ["semantic_similarity", "clustering"],
        "quality_tier": "excellent",
        "inference_speed": "slow",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 200,
        "languages": ["en"],
        "description": "Top MTEB benchmark scores for English. Best open embedding model available.",
        "best_for": "Production RAG pipelines and semantic search where quality is critical.",
        "tags": ["embedding", "bge", "rag", "high-quality", "large"],
        "requires_token": False,
        "license": "mit",
    },
    {
        "model_id": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        "display_name": "Multilingual MiniLM L12 (50 langs)",
        "category": "embedding",
        "provider": "huggingface",
        "param_count": "118M",
        "param_count_m": 118,
        "task_types": ["semantic_similarity", "clustering"],
        "quality_tier": "good",
        "inference_speed": "fast",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 200,
        "languages": ["multilingual"],
        "description": "Multilingual sentence embeddings for 50 languages with solid quality.",
        "best_for": "Multilingual semantic search and cross-lingual document clustering.",
        "tags": ["embedding", "multilingual", "sentence-transformers", "fast"],
        "requires_token": False,
        "license": "apache-2.0",
    },

    # ══════════════════════════════════════════════════════════════════════
    # VISION
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "google/vit-base-patch16-224",
        "display_name": "ViT Base (224px patches)",
        "category": "vision",
        "provider": "huggingface",
        "param_count": "86M",
        "param_count_m": 86,
        "task_types": ["image_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": True,
        "qlora_compatible": False,
        "training_data_min": 500,
        "languages": ["en"],
        "description": "Google's Vision Transformer pre-trained on ImageNet-21k. Best vision encoder baseline.",
        "best_for": "Image classification, visual fine-tuning with medium-to-large labelled datasets.",
        "tags": ["vision", "vit", "image-classification", "google"],
        "requires_token": False,
        "license": "apache-2.0",
    },
    {
        "model_id": "microsoft/resnet-50",
        "display_name": "ResNet-50",
        "category": "vision",
        "provider": "huggingface",
        "param_count": "25M",
        "param_count_m": 25,
        "task_types": ["image_classification"],
        "quality_tier": "good",
        "inference_speed": "fast",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 300,
        "languages": ["en"],
        "description": "Classic CNN backbone. Well-understood, fast, and easy to fine-tune on new visual domains.",
        "best_for": "Robust image classification when you need a battle-tested, interpretable baseline.",
        "tags": ["vision", "resnet", "cnn", "image-classification", "fast"],
        "requires_token": False,
        "license": "apache-2.0",
    },

    # ══════════════════════════════════════════════════════════════════════
    # CLOUD API FINE-TUNING
    # ══════════════════════════════════════════════════════════════════════
    {
        "model_id": "openai/gpt-3.5-turbo",
        "display_name": "GPT-3.5 Turbo (OpenAI fine-tune)",
        "category": "api",
        "provider": "openai",
        "param_count": "~20B",
        "param_count_m": 20000,
        "task_types": ["text_generation", "text_classification", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "fast",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 50,
        "languages": ["multilingual"],
        "description": "Fine-tune GPT-3.5 Turbo via the OpenAI API. No GPU required — billed per token.",
        "best_for": "Instruction following, customer support, and domain adaptation without any local compute.",
        "tags": ["api", "openai", "chat", "no-gpu-required", "cloud"],
        "requires_token": True,
        "license": "commercial",
    },
    {
        "model_id": "openai/gpt-4o-mini",
        "display_name": "GPT-4o Mini (OpenAI fine-tune)",
        "category": "api",
        "provider": "openai",
        "param_count": "~8B",
        "param_count_m": 8000,
        "task_types": ["text_generation", "text_classification", "question_answering"],
        "quality_tier": "excellent",
        "inference_speed": "fast",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 50,
        "languages": ["multilingual"],
        "description": "Smaller, cheaper GPT-4 variant. Fine-tunable via OpenAI API with great performance.",
        "best_for": "Cost-efficient advanced instruction following and classification via cloud API.",
        "tags": ["api", "openai", "gpt4", "no-gpu-required", "cloud"],
        "requires_token": True,
        "license": "commercial",
    },
    {
        "model_id": "cohere/command-r",
        "display_name": "Command R (Cohere fine-tune)",
        "category": "api",
        "provider": "cohere",
        "param_count": "35B",
        "param_count_m": 35000,
        "task_types": ["text_generation", "question_answering", "text_classification"],
        "quality_tier": "excellent",
        "inference_speed": "medium",
        "lora_compatible": False,
        "qlora_compatible": False,
        "training_data_min": 50,
        "languages": ["multilingual"],
        "description": "Cohere's Command R is optimised for RAG and tool use. Fine-tunable via Cohere API.",
        "best_for": "Enterprise RAG, retrieval-augmented generation, and tool-using agents.",
        "tags": ["api", "cohere", "rag", "no-gpu-required", "cloud"],
        "requires_token": True,
        "license": "commercial",
    },
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def get_model(model_id: str) -> dict | None:
    return next((m for m in CATALOG if m["model_id"] == model_id), None)


def filter_catalog(
    *,
    task_type: str | None = None,
    category: str | None = None,
    provider: str | None = None,
    max_params_m: int | None = None,
    language: str | None = None,
    lora_only: bool = False,
) -> list[dict]:
    results = CATALOG
    if task_type:
        results = [m for m in results if task_type in m["task_types"]]
    if category:
        results = [m for m in results if m["category"] == category]
    if provider:
        results = [m for m in results if m["provider"] == provider]
    if max_params_m is not None:
        results = [m for m in results if m["param_count_m"] <= max_params_m]
    if language:
        results = [m for m in results if language in m["languages"] or "multilingual" in m["languages"]]
    if lora_only:
        results = [m for m in results if m["lora_compatible"]]
    return results


def catalog_summary_for_prompt() -> str:
    """
    Compact text representation fed into ModelAgent's system prompt.
    Shows only huggingface models (API models aren't locally trainable).
    """
    lines = []
    for m in CATALOG:
        if m["provider"] != "huggingface":
            continue
        lora_flag = "LoRA✓" if m["lora_compatible"] else ""
        qlora_flag = "QLoRA✓" if m["qlora_compatible"] else ""
        flags = " ".join(f for f in [lora_flag, qlora_flag] if f)
        lines.append(
            f"• {m['model_id']} ({m['param_count']}, {m['quality_tier']}, "
            f"{m['inference_speed']} inference) [{m['category']}] {flags}\n"
            f"  Tasks: {', '.join(m['task_types'])}\n"
            f"  Best for: {m['best_for']}"
        )
    return "\n\n".join(lines)


# Legacy alias — keeps existing imports working
MODEL_CATALOG = CATALOG
